baseURL: https://neoswebsite.netlify.app/
languageCode: en-us
title: Portfolio website for Hao Ni
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      Hi, my name is Hao Ni. I am from China. I look forward to meeting you. Welcome to my website!
    title: Hao Ni
  blog: {}
  contact:
    address:
      - city: London
        country: UK
        street: Grov End Road
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: neo98ni@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: (44) 7536337318
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://www.github.com
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: Ni
    title: Hao
  tiles:
    enable: yes
    showcase:
      - image: basketball.jpeg
        subtitle: My experiences
        title: About me
        url: blogs/aliquam
      - image: world.jpeg
        subtitle: 1st Pre-Assignment
        title: Country Comparison
        url: blogs/tempus
      - image: drink.jpeg
        subtitle: Assignment 1
        title: Drink Consumption
        url: blogs/magna
      - image: climate.jpeg
        subtitle: Assignment 2a
        title: Climate change and temperature anomalies 
        url: blogs/ipsum
      - image: biden.jpeg
        subtitle: Assignment 2b
        title: Biden’s Approval Margins
        url: blogs/consequat
      - image: tfl.jpeg
        subtitle: Assignment 2 Challenge
        title: Excess rentals in TfL bike sharing
        url: blogs/etiam
  #two:
   # buttonText: Get Started
    #enable: yes
    #subtitle: "Find out more my details"
    #title: Learn more about me
    #url: blogs
